POST http://localhost/api/newUserReg
content-type: application/json

{
    "email": "nodejs.example.com",
    "password": "Kan272420",
    "name": "Mr. ノードJS"
}

###

POST http://localhost/api/newUserReg
content-type: application/json

 {
    "name": "API-GATEWAY",
    "password": "api-gateway",
    "email": "api_gateway@example.com"
}

###

POST http://localhost/api/login
Content-Type: application/json

{
    "email": "nodejs.example.com",
    "password": "Kan272420"
}

###
POST http://localhost/api/saveTest
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data":{
        "name" : "request wwwwwwwwwwww"
    }
    
}

###
POST http://localhost/api/getTestbyId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg"
}


###
POST http://localhost/api/updateTestByObjectId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data" :{
        "_id": "60ecfa73a00e25a7c744dcd4",
        "name": "変更したよーーーーーーppppppppppp！！",
        "id": 3
    }
}

###
POST http://localhost/api/deleteTestByObjectId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data" :{
        "_id": "60f19706a9521a5967d56594"
    }
}



###
POST http://localhost/api/saveTarget
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "name" : "筋トレ（テスト）",
        "themeColor" : "#1abc9c",
        "outcomes" : [
            {
                "name" : "スクワット",
                "unitName" : "回",
                "statisticsRule" : "Max",
                "defaultValue" : 20
            },
            {
                "name" : "腹筋",
                "unitName" : "回",
                "statisticsRule" : "Max",
                "defaultValue" : 20
            }
        ],
        "pinnedAtNavigationList" : true,
        "hiddenAtNavigationList" : true
    }
}


###
POST http://localhost/api/getTarget
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg"
}

###

POST http://localhost/api/updateTarget
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "_id": "60ef914ff7af2723ca26ff9b",
        "name" : "変更（テスト）",
        "themeColor" : "be-",
        "outcomes" : [
            {
                "name" : "変更",
                "unitName" : "変更",
                "statisticsRule" : "変更",
                "defaultValue" : 100
            },
            {
                "name" : "腹筋",
                "unitName" : "回",
                "statisticsRule" : "Max",
                "defaultValue" : 20
            }
        ],
        "pinnedAtNavigationList" : true,
        "hiddenAtNavigationList" : true
    }
}


###
POST http://localhost/api/deleteTarget
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data" :{
        "_id": "60ef914ff7af2723ca26ff9b"
    }
}

###

POST http://localhost/api/saveDocument
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "name": "testDocument!!!!!",
        "uri": "https://hirauchi-genta.com/kotlin-switch/",
        "targetId": "60ef8fc17540ec361fa9a3df"
    }
}

###
POST http://localhost/api/getDocumentByUserId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg"
}

###

POST http://localhost/api/updateDocument
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "_id": "60f1988c228f6a76e76ebb33",
        "name": "testUpdateDocument!!!!!",
        "uri": "https://gitlab.iroha-s.jp/techlid/front-end/-/blob/webapp/utils/sample-data.ts",
        "targetId": "60ef8fc17540ec361fa9a3df"
    }
}

###

POST http://localhost/api/deleteDocument
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "_id": "60f1b75e3b329f3c6b26ef8e"
    }
}


###

POST http://localhost/api/saveTerm
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "name": "testTerm2",
        "description": "testDescription2",
        "targetList": ["4529dkdd", "sjahfdkldl"],
        "startDatetimeScheduled": "2002-12-09",
        "endDatetimeScheduled": "2020-12-14",
        "startDatetime": "2020-12-30"
    }
}

###

POST http://localhost/api/getTermByUserId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg"
}

###

POST http://localhost/api/updateTerm
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "_id": "60f73de83dd4244de97b262f",
        "name": "testUpdateTerm2",
        "description": "testUpdateDescription2",
        "targetList": ["updated", "updated2"],
        "startDatetimeScheduled": "2021-12-01",
        "endDatetimeScheduled": "2021-12-19",
        "startDatetime": "2021-12-30"
    }
}

###

POST http://localhost/api/deleteTermByObjectId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "_id": "60f73aac51f18e02ece8ab53"
    }
}

###

POST http://localhost/api/saveTodo
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "name": "testsaveTodo3!!!",
        "startDatetimeScheduled": "2021-12-01T03:24:00",
        "timeInfoExisted": true,
        "processingTimeScheduled": 23,
        "repeatPattern": "weekly",
        "repeatDayForWeekly": [1, 2],
        "targetList": ["test1.2", "test2.2"],
        "term": "testtestesttestest2",
        "completed": true
    }
}

###

POST http://localhost/api/getTodoByUserId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg"
}

###

POST http://localhost/api/updateTodoByObjectId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
         "_id": "60f74e312bd6654da0c1ab5f",
        "name": "testupdateTodo2!!!",
        "startDatetimeScheduled": "2021-12-01T03:24:00",
        "timeInfoExisted": true,
        "processingTimeScheduled": 100,
        "repeatPattern": "weekly",
        "repeatDayForWeekly": [3, 4],
        "targetList": ["update1.2", "update2.2"],
        "term": "updateupdate",
        "completed": true
    }
}

###

POST http://localhost/api/deleteTodoByObjectId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "_id": "60f74e312bd6654da0c1ab5f"
    }
}

###

POST http://localhost/api/saveHabit
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "name": "testSaveHabit2",
        "target": "60ef8fc17540ec361fa9a3df"
    }
}

###

POST http://localhost/api/getHabitByUserId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg"
}

###

POST http://localhost/api/updateHabitByObjectId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "_id": "60f77b99dbbc91e14fd2fa46",
        "name": "tsetupdateHabit1",
        "target": "60ef8fc17540ec361fa9a3df"
    }
}

###

POST http://localhost/api/deleteHabitByObjectId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "_id": "60f77b99dbbc91e14fd2fa46"
    }
}

###

POST http://localhost/api/saveTodoArchive
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "todoId": "6108dec3999f8d48ab580a19",
        "checkInDateTime": "2021-12-01T03:24:00",
        "targets": ["60ef8fc17540ec361fa9a3df"],
        "statistics":{
            "6108de34999f8dd93b580a17":[
                {
                    "targetId": "",
                    "name": "testsample",
                    "unitname": "tete",
                    "statisticsRule": "test",
                    "defaultValue": 10,
                    "value": 5,
                    "feelingText": "testtext",
                    "feelingName": "testName",
                    "positivePercent": 10,
                    "negativePercent": 5,
                    "recordingDateTime": "2021-12-01T03:24:00"
                }
            ],
            "6108de34999f8d839f580a18":[
                {
                    "targetId": "",
                    "name": "testsample",
                    "unitname": "tete",
                    "statisticsRule": "test",
                    "defaultValue": 10,
                    "value": 5,
                    "feelingText": "testtext",
                    "feelingName": "testName",
                    "positivePercent": 10,
                    "negativePercent": 5,
                    "recordingDateTime": "2021-12-01T03:24:00"
                }
            ]
        }
    }
}

###

POST http://localhost/api/getTodoArchiveByUserId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg"
}

###


POST http://localhost/api/deleteTodoArchiveByObjectId
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data": {
        "_id": "6108df94999f8d60ec580a1a"
    }
}

###

POST http://localhost/api/saveArchive
Content-Type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg",
    "data":{
        "todoId":"1",
        "checkInDateTime":"2021-12-02T03:24:00",
        "feelingAndDiary":{
            "diaryFlag":true,
            "feelingFlag":true,
            "textForDiary":"testの日記です",
            "positiveValue":4,
            "negativeValue":2
        },
        "outcomes":[
            {
                "outcomeId":"1",
                "value":10,
                "name" : "腹筋",
                "unitName" : "回",
                "statisticsRule ": ""
            },
            {
                "outcomeId":"2",
                "value":10,
                "name" : "udetate",
                "unitName" : "回",
                "statisticsRule ": ""
            }
        ]
    }
}

###


POST http://localhost/api/getOutcomeArchiveByUserId
Content-Type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg"
}

###

POST http://localhost/api/getFeelingAndDiaryArchivesByUserId
Content-Type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg"
}

###

POST http://localhost/api/getFeelingArchiveByUserId
Content-Type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg"
}

###



















