POST http://localhost:4002/newUserReg
content-type: application/json

{
    "email": "nodejs.example.com",
    "password": "Kan272420",
    "name": "Mr. ノードJS"
}

###

POST http://localhost:4002/newUserReg
content-type: application/json

 {
    "name": "API-GATEWAY",
    "password": "api-gateway",
    "email": "api_gateway@example.com"
}

###

POST http://localhost:4002/login
Content-Type: application/json

{
    "email": "api_gateway@example.com",
    "password": "api-gateway"
}

###
POST http://localhost:4002/toOngoingData
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.-RmolK2yznBtDt3jnaLmIdMQEMrqSI9l57yGepBQUIg"
}
